name: Verifica Connessione di Rete

on: [push, pull_request]

jobs:
  check_network:
    runs-on: ubuntu-latest

    steps:
      

      - name: Verifica connessione ping
        run: ping -c 5 bing.com
